name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy 🚀
        run: make deploy
